import Head from 'next/head'
import Image from 'next/image'
import {useState} from "react";
import axios from 'axios';
import nProgress from "nprogress";
import {Router} from "next/router";
import Link from "next/link";

export default function Home() {
    const [video,setVideo] = useState()
    const [sources,setSources] = useState([])
    const [url,setUrl] = useState("")
    const VideoApi = () => {
        if (url != "")
        {
            nProgress.start();
            axios.get('http://localhost:5000/api/youtube/mp4?url=' + url ).then(res => {
                setVideo(res.data.info)
                setSources(res.data.sources)
                nProgress.done()
                // Router.events.on("routeChangeComplete", nProgress.done);
            })
                .catch(e => {
                    alert('Video Bulunamadı')
                    nProgress.done()
                });
            ;

        }
    }

    return (
        <div>
            <Head>
                <title>Video Dönüştürücü</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />


            </Head>

            <main>
                <div className="Centers">
                    <div className="container">
                        <div className="col-md-7 col-12" style={{margin:"0 auto 0 auto"}} >
                            <div style={{textAlign:"center",color:"white",fontFamily:"anton",fontSize:"50px"}}>
                                <img src="ytlogo.png" width="50" />
                            </div>
                            <div style={{textAlign:"center",color:"white",fontFamily:"anton",fontSize:"80px"}}>
                                Youtube Video Dönüştür
                            </div>
                            <p  style={{textAlign:"center",color:"#ffffffb3",fontSize:"20px"}}>
                                <Link href="/youtube-mp4">Başlamak İçin Tıkla</Link></p>
                        </div>

                    </div>
                </div>
            </main>
        </div>
    )
}
