import Head from 'next/head'
import Image from 'next/image'
import {useState} from "react";
import axios from 'axios';
import nProgress from "nprogress";
import {Router} from "next/router";

export default function Home() {
  const [video,setVideo] = useState()
  const [sources,setSources] = useState([])
  const [url,setUrl] = useState("")
  const VideoApi = () => {
      if (url != "")
      {
          nProgress.start();
          axios.get('http://localhost:5000/api/youtube/mp4?url=' + url ).then(res => {
              setVideo(res.data.info)
              setSources(res.data.sources)
              nProgress.done()
              // Router.events.on("routeChangeComplete", nProgress.done);
          })
          .catch(e => {
              alert('Video Bulunamadı')
              nProgress.done()
          });
          ;

      }
  }

  return (
    <div>
      <Head>
        <title>Video Dönüştürücü</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />


      </Head>

      <main>
          <div className="Centers">
              <div className="container">
                      <div className="col-md-7 col-12" style={{margin:"0 auto 0 auto"}} >
                          <div style={{textAlign:"center",color:"white",fontFamily:"anton",fontSize:"50px"}}>
                              <img src="ytlogo.png" width="50" />
                          </div>
                          <div style={{textAlign:"center",color:"white",fontFamily:"anton",fontSize:"50px"}}>
                              Youtube Video Dönüştürücü
                          </div>
                          <p style={{textAlign:"center",color:"#ffffffb3",fontSize:"20px"}}>Erdem Koray Şanlı</p>
                          <div className="p-2 p-m-2" style={{height:"70px"}}>
                              <input onChange={(e) => setUrl(e.target.value)} value={url} placeholder="Video Url'sini Yapıştırınız" style={{textAlign:"center"}} className="col-12 form-control"/>
                          </div>
                          <div className="p-2" style={{height:"65px"}}>
                              <input onClick={() => VideoApi()}  className="col-12 btn btn-light" value="Videoyu Dönüştür" style={{height:"100%",fontFamily:"anton",fontSize:"17px"}}/>
                          </div>
                      </div>

              {video ?
              <div className="VideoInfo col-md-7 col-12 p-1">
                  <div className="FloatLeft col-md-5 col-12 p-2 ">
                      <img src={video.thumbnail} className="col-12"/>
                  </div>
                  <div className="col-md-7 col-12 p-3" style={{margin: "0 0 10px 0", float: "left"}}>
                      <div className="col-12"
                           style={{float: "left", color: "white", fontFamily: "anton", fontSize: "20px"}}>
                          {video.title}
                      </div>
                      <div className="col-12" style={{float: "left"}}>
                          <p style={{color: "#ffffffb3", fontSize: "15px"}}>
                              {video.description.substring(0,180) + "..."}
                          </p>
                      </div>
                      <div className="FloatLeft col-12">
                          <div className="VideoDetailTop FloatLeft col-4">Süre</div>
                          <div className="VideoDetailTop FloatLeft col-4">İzlenme</div>
                          <div className="VideoDetailTop FloatLeft col-4">Yükleyen</div>
                      </div>

                      <div className="col-12" style={{float: "left"}}>
                          <div className="col-4 p-1" style={{height: "auto",wordBreak:"break-word", float: "left"}}>
                              <div className="VideoDetailBottom col-12 p-1">{video.lenght}</div>
                          </div>
                          <div className="col-4 p-1" style={{height: "auto",wordBreak:"break-word", float: "left"}}>
                              <div className="VideoDetailBottom col-12 p-1">{
                                  video.views.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".")
                                  }</div>
                          </div>
                          <div className="col-4 p-1" style={{height: "auto",wordBreak:"break-word", float: "left"}}>
                              <div className="VideoDetailBottom col-12 p-1">{video.channel}</div>
                          </div>
                      </div>

                      <div style={{clear: "both"}}></div>

                  </div>
              </div> : null }


              {sources.map((item,$key) => {
                  return(
                  <div  key={$key} className="col-md-7 col-11 p-2 Quality" >
                      <div className="col-md-4 col-12 ColorWhite FloatLeft">
                          <div className="FloatLeft p-2" >
                              <span  style={{textAlign:"center","border-right": "1px solid white",paddingRight:"15px",fontFamily:"anton",fontSize:"16px"}}>Kalite</span>
                          </div>
                          <div className="FloatLeft p-2" style={{textAlign:"center",fontFamily:"anton",fontSize:"16px"}}>
                              {item.resolution}
                          </div>
                      </div>

                      <div className="col-md-4 col-12 ColorWhite FloatLeft">
                          <div className="FloatLeft p-2" >
                              <span  style={{"border-right": "1px solid white",paddingRight:"15px",fontFamily:"anton",fontSize:"16px"}}>Dosya Boyutu</span>
                          </div>
                          <div className="FloatLeft p-2" style={{fontFamily:"anton",fontSize:"16px"}}>
                              {
                                  (item.filesize / 1000000).toFixed(0) + " MB"}
                          </div>
                      </div>
                      <div className="col-md-4 col-12 ColorWhite FloatLeft">
                          <div className="col-12 p-1  DownloadDiv">
                              <a className="col-12 p-1 DownloadButton" download  target="_blank" href={item.url + "&title=" + video.title} type="button" >İndir</a>
                          </div>
                      </div>
                      {/*<div className="col-4 ColorWhite" style={{"border-right": "2px solid white"}}>*/}

                      {/*</div>*/}

                  </div>
                  )

              }) }

              </div>
          </div>
      </main>
    </div>
  )
}
